In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [4]:
from sklearn.datasets import load_iris

In [6]:
data=load_iris()
x=data.data
y=data.target

In [8]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=1)

In [16]:
x_train.shape,x_test.shape

((100, 4), (50, 4))

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler

StandardScaler()

In [22]:
x_train=scaler.fit_transform(x_train)

In [24]:
x_train

array([[-0.85266944,  0.88903171, -1.29564086, -1.2984507 ],
       [-0.36957061,  1.13127468, -1.40969376, -1.2984507 ],
       [ 2.28747298,  1.8580036 ,  1.66973435,  1.28553079],
       [ 1.32127531,  0.16230279,  0.92839055,  1.15633171],
       [ 1.80437415, -0.32218315,  1.44162857,  0.76873449],
       [ 0.71740177, -0.56442613,  1.04244344,  1.28553079],
       [ 0.47585235, -0.56442613,  0.58623187,  0.76873449],
       [ 0.23430293,  0.88903171,  0.41515253,  0.51033634],
       [ 2.28747298, -0.56442613,  1.66973435,  1.02713264],
       [-0.12802119, -0.07994018,  0.24407319, -0.00645995],
       [-1.21499357,  0.88903171, -1.23861442, -1.2984507 ],
       [-0.12802119, -1.29115505,  0.70028476,  1.02713264],
       [ 0.59662706, -0.8066691 ,  0.64325832,  0.76873449],
       [-1.21499357, -0.07994018, -1.35266731, -1.42764977],
       [-1.33576828,  0.40454576, -1.40969376, -1.2984507 ],
       [ 0.83817648, -0.07994018,  1.15649633,  1.28553079],
       [-1.45654298,  0.

In [26]:
from sklearn.decomposition import PCA

In [28]:
pca=PCA()

In [30]:
pca


PCA()

In [32]:
x_train=pca.fit_transform(x_train)

In [34]:
x_train

array([[-2.13962242e+00,  5.13610868e-01, -1.99419486e-01,
        -2.31008729e-02],
       [-1.99540185e+00,  8.82301128e-01, -5.29591179e-01,
        -2.21415708e-01],
       [ 2.56560809e+00,  2.52456203e+00, -3.36324212e-01,
         2.37570906e-01],
       [ 1.88179210e+00,  6.13593714e-01, -9.89270342e-02,
        -2.09039180e-01],
       [ 2.32153724e+00,  2.67012730e-01, -7.22437857e-01,
         2.14630593e-01],
       [ 1.84467374e+00, -2.44516671e-01,  3.16505830e-01,
        -9.86626870e-02],
       [ 1.15280787e+00, -3.50084715e-01,  1.09329969e-01,
        -1.27100336e-01],
       [ 4.79050797e-01,  9.52879660e-01,  3.61253884e-01,
         1.00480704e-01],
       [ 2.91219047e+00,  1.91581270e-01, -9.30781970e-01,
         1.01054283e-01],
       [ 8.67557056e-02, -1.11609550e-01,  1.08336251e-01,
         2.25107361e-01],
       [-2.30153266e+00,  4.10609890e-01,  7.68242776e-02,
         1.23172991e-01],
       [ 1.18919390e+00, -1.19987449e+00,  6.06574629e-01,
      

In [38]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=1)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)


pca = PCA(n_components=4)
x_train = pca.fit_transform(x_train)